# LOF - multi-run experiments

In [2]:
import sys
import time
import json
import gc
from pathlib import Path

import numpy as np
import pandas as pd
import optuna
from sklearn.neighbors import LocalOutlierFactor
from sklearn.metrics import roc_auc_score

sys.path.append("../src")
from data import make_optuna_subsample, make_final_subsample
from optuna_utils import run_study
from metrics import find_best_f1_threshold, minmax_scale_scores, evaluate_scores, print_metrics
from results import build_experiment_record, save_record_json, get_memory_mb

In [3]:
RESULTS_DIR = Path("../results")
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR = Path("../models")
MODELS_DIR.mkdir(parents=True, exist_ok=True)

DATASETS = ["CICIDS", "UNSW_NB15"]
SEED = 29
N_TRIALS = 200

DATASET_VERSION = "v1"
PREPROCESSING_VERSION = "v1"
SPLIT_METHOD = "stratified_train_val_test_fixed_seed"
MODEL_TYPE = "LOF"
FUSION_STRATEGY = "none"

RUN_CONFIGS = [
    dict(run_index=1, n_train_opt=7000,  n_val_opt=3000,
         n_train_final=154000, n_val_final=66000, n_test_final=100000,
         notes="run1_small_opt_sample"),
    dict(run_index=2, n_train_opt=21000, n_val_opt=9000,
         n_train_final=154000, n_val_final=66000, n_test_final=100000,
         notes="run2_medium_opt_sample"),
    dict(run_index=3, n_train_opt=35000, n_val_opt=15000,
         n_train_final=154000, n_val_final=66000, n_test_final=100000,
         notes="run3_large_opt_sample"),
]

In [4]:
def make_objective(train_x, train_y, val_x, val_y):
    def objective(trial):
        n_pos = int(val_y.sum())
        n_neg = len(val_y) - n_pos
        if n_pos < 5 or n_neg < 5:
            raise optuna.exceptions.TrialPruned()

        n_neighbors = trial.suggest_int("n_neighbors", 5, 100, log=True)
        leaf_size = trial.suggest_int("leaf_size", 10, 60, step=10)
        metric = trial.suggest_categorical("metric", ["minkowski", "euclidean", "manhattan"])
        contamination = trial.suggest_float("contamination", 0.01, 0.5)
        p = trial.suggest_int("p", 1, 2) if metric == "minkowski" else 2

        try:
            clf = LocalOutlierFactor(
                n_neighbors=n_neighbors,
                leaf_size=leaf_size,
                metric=metric,
                p=p,
                contamination=contamination,
                novelty=True,
                n_jobs=-1,
            )
            clf.fit(train_x)
            val_scores = -clf.score_samples(val_x)
            auc = roc_auc_score(val_y, val_scores)
        except ValueError:
            raise optuna.exceptions.TrialPruned()

        return auc
    return objective

In [5]:
def fit_and_score_lof(params, train_x, train_y, val_x, test_x):
    clf = LocalOutlierFactor(
        n_neighbors=params["n_neighbors"],
        leaf_size=params["leaf_size"],
        metric=params["metric"],
        p=params.get("p", 2),
        contamination=params["contamination"],
        novelty=True,
        n_jobs=-1,
    )

    gc.collect()
    mem_before = get_memory_mb()

    start_train = time.time()
    clf.fit(train_x)
    runtime_train = time.time() - start_train
    mem_after_train = get_memory_mb()

    val_scores_raw = -clf.score_samples(val_x)
    scores_val = minmax_scale_scores(val_scores_raw)

    start_inference = time.time()
    test_scores_raw = -clf.score_samples(test_x)
    runtime_inference = time.time() - start_inference
    mem_after_inference = get_memory_mb()

    scores_test = minmax_scale_scores(test_scores_raw)
    memory_peak = max(mem_before, mem_after_train, mem_after_inference)

    return clf, scores_val, scores_test, runtime_train, runtime_inference, memory_peak

In [6]:
def run_experiment(dataset, run_cfg):
    run_index = run_cfg["run_index"]
    study_name = f"LOF_{dataset}_run{run_index}"

    train_x, train_y, val_x, val_y = make_optuna_subsample(
        dataset, SEED, run_cfg["n_train_opt"], run_cfg["n_val_opt"]
    )
    objective = make_objective(train_x, train_y, val_x, val_y)
    study = run_study(objective, study_name, SEED, N_TRIALS, results_dir=RESULTS_DIR)

    train_x, train_y, val_x, val_y, test_x, test_y = make_final_subsample(
        dataset, SEED,
        run_cfg["n_train_final"], run_cfg["n_val_final"], run_cfg["n_test_final"],
    )

    clf, scores_val, scores_test, runtime_train, runtime_inference, memory_peak = fit_and_score_lof(
        study.best_params, train_x, train_y, val_x, test_x
    )

    best_threshold, best_f1_val, best_prec_val, best_rec_val = find_best_f1_threshold(val_y, scores_val)
    print(f"[{dataset} run{run_index}] threshold={best_threshold:.4f} "
          f"F1={best_f1_val:.4f} P={best_prec_val:.4f} R={best_rec_val:.4f}")

    metrics = evaluate_scores(test_y, scores_test, threshold=best_threshold)
    print_metrics(f"LOF final - {dataset} run{run_index}", metrics)

    model_dir = MODELS_DIR / MODEL_TYPE
    model_dir.mkdir(parents=True, exist_ok=True)
    model_path = model_dir / f"{dataset}_run{run_index}.joblib"
    joblib.dump(clf, model_path)

    record = build_experiment_record(
        dataset_name=dataset,
        dataset_version=DATASET_VERSION,
        split_method=SPLIT_METHOD,
        seed=SEED,
        preprocessing_version=PREPROCESSING_VERSION,
        model_type=MODEL_TYPE,
        fusion_strategy=FUSION_STRATEGY,
        hyperparameters=study.best_params,
        threshold=best_threshold,
        scores_test=scores_test,
        test_y=test_y,
        runtime_train=runtime_train,
        runtime_inference=runtime_inference,
        memory_peak=memory_peak,
        notes=run_cfg["notes"],
    )
    save_record_json(record, RESULTS_DIR, run_index, MODEL_TYPE, dataset)
    return record

In [7]:
all_records = []

In [7]:
rec = run_experiment(DATASETS[0], RUN_CONFIGS[0])
all_records.append(rec)
pd.DataFrame(all_records)

[I 2026-07-27 10:56:40,826] A new study created in memory with name: LOF_CICIDS_run1

CICIDS optuna subsample -> train: 7000, val: 3000 (val positives: 726)

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-07-27 10:56:43,145] Trial 0 finished with value: 0.6952612597551431 and parameters: {'n_neighbors': 66, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.2757254682642995}. Best is trial 0 with value: 0.6952612597551431.
[I 2026-07-27 10:56:43,964] Trial 1 finished with value: 0.800300316671149 and parameters: {'n_neighbors': 43, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.362951259351822, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:44,770] Trial 2 finished with value: 0.6087445575932022 and parameters: {'n_neighbors': 16, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4220506703403939}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:45,583] Trial 3 finished with value: 0.753573756272245 and parameters: {'n_neighbors': 56, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.24751720505560543}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:45,964] Trial 4 finished with value: 0.7198020623602297 and parameters: {'n_neighbors': 35, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.07322948745198661}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:46,756] Trial 5 finished with value: 0.7715273386297613 and parameters: {'n_neighbors': 33, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.2505606416873945}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:47,576] Trial 6 finished with value: 0.7668308777387693 and parameters: {'n_neighbors': 47, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.16069334497735088}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:47,992] Trial 7 finished with value: 0.7003508338360821 and parameters: {'n_neighbors': 96, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.12591914309334096, 'p': 2}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:48,791] Trial 8 finished with value: 0.7546943408660847 and parameters: {'n_neighbors': 55, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.028572769154841735}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:49,159] Trial 9 finished with value: 0.6666866554729352 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.2059589309270761}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:49,944] Trial 10 finished with value: 0.5083707669159816 and parameters: {'n_neighbors': 6, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.4896162581121494, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:50,742] Trial 11 finished with value: 0.7112953109894822 and parameters: {'n_neighbors': 26, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.36019245364383135, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:51,117] Trial 12 finished with value: 0.6611988195701316 and parameters: {'n_neighbors': 24, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.3305071925650102, 'p': 2}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:51,916] Trial 13 finished with value: 0.6087445575932022 and parameters: {'n_neighbors': 16, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.3356699361960016}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:52,714] Trial 14 finished with value: 0.7003720340851547 and parameters: {'n_neighbors': 25, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.4145384485821778, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:53,508] Trial 15 finished with value: 0.5202625923422277 and parameters: {'n_neighbors': 9, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.28568368191441673}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:53,906] Trial 16 finished with value: 0.7198020623602297 and parameters: {'n_neighbors': 35, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.207488968416297, 'p': 2}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:54,744] Trial 17 finished with value: 0.7765948038795245 and parameters: {'n_neighbors': 89, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.39801388577926966}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:55,577] Trial 18 finished with value: 0.7826701895423411 and parameters: {'n_neighbors': 76, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.481452581127811, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:56,395] Trial 19 finished with value: 0.7775055060075449 and parameters: {'n_neighbors': 72, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.49566036239447236, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:57,202] Trial 20 finished with value: 0.796687794229171 and parameters: {'n_neighbors': 44, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.4491433159233426, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:58,025] Trial 21 finished with value: 0.7668308777387693 and parameters: {'n_neighbors': 47, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.4571569001259982, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:58,839] Trial 22 finished with value: 0.799640686064289 and parameters: {'n_neighbors': 41, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.4387344806087562, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:56:59,657] Trial 23 finished with value: 0.799640686064289 and parameters: {'n_neighbors': 41, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.3783495579329735, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:57:00,468] Trial 24 finished with value: 0.6465773106454324 and parameters: {'n_neighbors': 21, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.37303825476705654, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:57:01,276] Trial 25 finished with value: 0.7715273386297613 and parameters: {'n_neighbors': 33, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.3278311165772784, 'p': 1}. Best is trial 1 with value: 0.800300316671149.
[I 2026-07-27 10:57:02,093] Trial 26 finished with value: 0.8031999050228841 and parameters: {'n_neighbors': 42, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.3808037127545823, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:02,485] Trial 27 finished with value: 0.7086107537354839 and parameters: {'n_neighbors': 56, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.4390590578621922}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:03,284] Trial 28 finished with value: 0.7317426483593431 and parameters: {'n_neighbors': 28, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.30209596028168345, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:03,656] Trial 29 finished with value: 0.6273501990400527 and parameters: {'n_neighbors': 19, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.3934412376745427}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:04,475] Trial 30 finished with value: 0.7610898502898982 and parameters: {'n_neighbors': 64, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.35382134977508956, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:05,284] Trial 31 finished with value: 0.800300316671149 and parameters: {'n_neighbors': 43, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.37972841382393246, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:06,100] Trial 32 finished with value: 0.799640686064289 and parameters: {'n_neighbors': 41, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.4284436830477493, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:06,935] Trial 33 finished with value: 0.7546943408660847 and parameters: {'n_neighbors': 55, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.30337886232983224, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:07,749] Trial 34 finished with value: 0.7669692850791435 and parameters: {'n_neighbors': 32, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.4143960739074661, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:08,569] Trial 35 finished with value: 0.799640686064289 and parameters: {'n_neighbors': 41, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.45720539196440957, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:08,965] Trial 36 finished with value: 0.6973040551836426 and parameters: {'n_neighbors': 62, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.3982338108740378}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:09,792] Trial 37 finished with value: 0.7828691690229229 and parameters: {'n_neighbors': 81, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.2693803233659711, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:10,610] Trial 38 finished with value: 0.7617201034087577 and parameters: {'n_neighbors': 51, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.3530332622517471, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:11,415] Trial 39 finished with value: 0.7421165359519881 and parameters: {'n_neighbors': 29, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.3168601661895371, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:11,792] Trial 40 finished with value: 0.7291964984457188 and parameters: {'n_neighbors': 38, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.4707109996496887}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:12,624] Trial 41 finished with value: 0.7676434529996536 and parameters: {'n_neighbors': 46, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.3736837595881307, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:13,465] Trial 42 finished with value: 0.7891241510814548 and parameters: {'n_neighbors': 37, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.3936116026677048, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:14,256] Trial 43 finished with value: 0.7527611810113609 and parameters: {'n_neighbors': 30, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.3754797113155273, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:15,074] Trial 44 finished with value: 0.762131388240767 and parameters: {'n_neighbors': 50, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.35001420570760006, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:15,885] Trial 45 finished with value: 0.8031999050228841 and parameters: {'n_neighbors': 42, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.43332918370028484, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:16,777] Trial 46 finished with value: 0.658977942049422 and parameters: {'n_neighbors': 22, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.4155626413301686}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:17,180] Trial 47 finished with value: 0.6952612597551431 and parameters: {'n_neighbors': 66, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.42704521350959956, 'p': 2}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:17,999] Trial 48 finished with value: 0.7835430340827318 and parameters: {'n_neighbors': 36, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.08337456879906935, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:18,799] Trial 49 finished with value: 0.5083707669159816 and parameters: {'n_neighbors': 6, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.22166196213850642, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:19,632] Trial 50 finished with value: 0.763094485270067 and parameters: {'n_neighbors': 99, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.46990904916698906}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:20,457] Trial 51 finished with value: 0.7997884820863953 and parameters: {'n_neighbors': 40, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.37446454395577894, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:21,277] Trial 52 finished with value: 0.762131388240767 and parameters: {'n_neighbors': 50, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.4363410392665278, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:22,096] Trial 53 finished with value: 0.8031999050228841 and parameters: {'n_neighbors': 42, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.34025819616888797, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:22,915] Trial 54 finished with value: 0.7192033067542782 and parameters: {'n_neighbors': 27, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.3414270652730654, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:23,714] Trial 55 finished with value: 0.7715273386297613 and parameters: {'n_neighbors': 33, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.2852863468181946, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:24,554] Trial 56 finished with value: 0.800300316671149 and parameters: {'n_neighbors': 43, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.30275812849357586, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:24,951] Trial 57 finished with value: 0.7036380838851455 and parameters: {'n_neighbors': 58, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.25967612817327446, 'p': 2}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:25,332] Trial 58 finished with value: 0.7304061240856635 and parameters: {'n_neighbors': 46, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.31333183725548064}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:26,117] Trial 59 finished with value: 0.5833920883093346 and parameters: {'n_neighbors': 13, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.1674618592344237}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:26,952] Trial 60 finished with value: 0.7759899910595522 and parameters: {'n_neighbors': 71, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.33156785107943987, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:27,777] Trial 61 finished with value: 0.800300316671149 and parameters: {'n_neighbors': 43, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.3657353124117679, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:28,591] Trial 62 finished with value: 0.796687794229171 and parameters: {'n_neighbors': 44, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.24307703458725466, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:29,415] Trial 63 finished with value: 0.7604420312503787 and parameters: {'n_neighbors': 52, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.4046981793635388, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:30,214] Trial 64 finished with value: 0.7751119978872437 and parameters: {'n_neighbors': 35, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.3614328507531146, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:31,054] Trial 65 finished with value: 0.7584558707729733 and parameters: {'n_neighbors': 60, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.2924734202802707, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:31,846] Trial 66 finished with value: 0.7669692850791435 and parameters: {'n_neighbors': 32, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.3843214695913432, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:32,679] Trial 67 finished with value: 0.796687794229171 and parameters: {'n_neighbors': 44, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.32936472569246406, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:33,496] Trial 68 finished with value: 0.793645861347948 and parameters: {'n_neighbors': 38, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.3616571865547124, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:34,309] Trial 69 finished with value: 0.7003720340851547 and parameters: {'n_neighbors': 25, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.31679682375914764, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:34,695] Trial 70 finished with value: 0.7115990802726231 and parameters: {'n_neighbors': 53, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.3442223996054137}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:35,513] Trial 71 finished with value: 0.7997884820863953 and parameters: {'n_neighbors': 40, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.38442168971218177, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:36,339] Trial 72 finished with value: 0.800300316671149 and parameters: {'n_neighbors': 43, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.36728929526053183, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:37,157] Trial 73 finished with value: 0.7668308777387693 and parameters: {'n_neighbors': 47, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.4122328558060097, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:37,972] Trial 74 finished with value: 0.7527611810113609 and parameters: {'n_neighbors': 30, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.3637052814931549, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:38,797] Trial 75 finished with value: 0.796687794229171 and parameters: {'n_neighbors': 44, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.3086110523852058, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:39,589] Trial 76 finished with value: 0.7751119978872437 and parameters: {'n_neighbors': 35, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.34218453728000514, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:40,410] Trial 77 finished with value: 0.7665125711419787 and parameters: {'n_neighbors': 49, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.39084131413760537}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:41,230] Trial 78 finished with value: 0.7560220821794341 and parameters: {'n_neighbors': 57, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.40460047661218684, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:42,047] Trial 79 finished with value: 0.8031999050228841 and parameters: {'n_neighbors': 42, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.32565594038048923, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.
[I 2026-07-27 10:57:42,890] Trial 80 finished with value: 0.766803620275676 and parameters: {'n_neighbors': 67, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.2897899963441206, 'p': 1}. Best is trial 26 with value: 0.8031999050228841.

,experiment_id,dataset_name,dataset_version,split_method,seed,preprocessing_version,model_type,fusion_strategy,hyperparameters,threshold,...,AUC_ROC,AUC_PR,Precision,Recall,F1,ConfusionMatrix,runtime_train,runtime_inference,memory_peak,notes
0,c278dda5-cfb1-4d09-80ec-b3cd40a206b6,CICIDS,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 42, 'leaf_size': 40, 'metric':...",7.906182e-11,...,0.798456,0.492324,0.483001,0.826058,0.609578,"[[54374, 21411], [4212, 20003]]",220.067883,143.144763,2089.921875,run1_small_opt_sample

In [8]:
rec = run_experiment(DATASETS[1], RUN_CONFIGS[0])
all_records.append(rec)
pd.DataFrame(all_records)

[I 2026-07-27 11:09:16,314] A new study created in memory with name: LOF_UNSW_NB15_run1

UNSW_NB15 optuna subsample -> train: 7000, val: 3000 (val positives: 2042)

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-07-27 11:09:16,765] Trial 0 finished with value: 0.8518118468323862 and parameters: {'n_neighbors': 66, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.2757254682642995}. Best is trial 0 with value: 0.8518118468323862.
[I 2026-07-27 11:09:18,355] Trial 1 finished with value: 0.8687550990780254 and parameters: {'n_neighbors': 43, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.362951259351822, 'p': 1}. Best is trial 1 with value: 0.8687550990780254.
[I 2026-07-27 11:09:19,918] Trial 2 finished with value: 0.8872659024780242 and parameters: {'n_neighbors': 16, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4220506703403939}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:21,494] Trial 3 finished with value: 0.8668519544676614 and parameters: {'n_neighbors': 56, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.24751720505560543}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:21,925] Trial 4 finished with value: 0.8573180843211147 and parameters: {'n_neighbors': 35, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.07322948745198661}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:23,509] Trial 5 finished with value: 0.8705222682743801 and parameters: {'n_neighbors': 33, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.2505606416873945}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:25,089] Trial 6 finished with value: 0.8683205911761157 and parameters: {'n_neighbors': 47, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.16069334497735088}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:25,515] Trial 7 finished with value: 0.8084362009491697 and parameters: {'n_neighbors': 96, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.12591914309334096, 'p': 2}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:27,098] Trial 8 finished with value: 0.8671581547420659 and parameters: {'n_neighbors': 55, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.028572769154841735}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:27,499] Trial 9 finished with value: 0.8692744638172489 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.2059589309270761}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:29,074] Trial 10 finished with value: 0.8649986504695752 and parameters: {'n_neighbors': 6, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.4896162581121494}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:30,658] Trial 11 finished with value: 0.8834693257868683 and parameters: {'n_neighbors': 20, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.38254436443147066}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:32,223] Trial 12 finished with value: 0.884537192854032 and parameters: {'n_neighbors': 19, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.42186787781970714}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:33,789] Trial 13 finished with value: 0.884627928327666 and parameters: {'n_neighbors': 12, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4886147399526398}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:35,357] Trial 14 finished with value: 0.8759272909812519 and parameters: {'n_neighbors': 8, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.49373905782197614}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:36,915] Trial 15 finished with value: 0.8810102666549435 and parameters: {'n_neighbors': 10, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.4283364941417253, 'p': 1}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:38,473] Trial 16 finished with value: 0.8693810460496586 and parameters: {'n_neighbors': 5, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.31791812834395955}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:40,054] Trial 17 finished with value: 0.8868464745562397 and parameters: {'n_neighbors': 13, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4305570896993283}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:40,480] Trial 18 finished with value: 0.8686112002846282 and parameters: {'n_neighbors': 22, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.33349120442142083, 'p': 2}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:40,898] Trial 19 finished with value: 0.865844407320998 and parameters: {'n_neighbors': 8, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.420160722838791}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:42,439] Trial 20 finished with value: 0.8872181066088141 and parameters: {'n_neighbors': 15, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.4450867602057534}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:44,036] Trial 21 finished with value: 0.8872181066088141 and parameters: {'n_neighbors': 15, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.4426938406342119}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:45,610] Trial 22 finished with value: 0.8774299215432085 and parameters: {'n_neighbors': 26, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.3822086340463531}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:47,185] Trial 23 finished with value: 0.8872659024780242 and parameters: {'n_neighbors': 16, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.4614490507455496}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:48,769] Trial 24 finished with value: 0.8868055796948835 and parameters: {'n_neighbors': 17, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.34138313529951814}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:50,362] Trial 25 finished with value: 0.8774299215432085 and parameters: {'n_neighbors': 26, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.45961770459620427}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:51,935] Trial 26 finished with value: 0.8810102666549435 and parameters: {'n_neighbors': 10, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.38877995987724023}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:53,546] Trial 27 finished with value: 0.8810102666549435 and parameters: {'n_neighbors': 10, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4589502301416634}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:53,963] Trial 28 finished with value: 0.8662980846891684 and parameters: {'n_neighbors': 25, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.3008322455390682}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:55,536] Trial 29 finished with value: 0.8868055796948835 and parameters: {'n_neighbors': 17, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.40255447647334264, 'p': 1}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:55,969] Trial 30 finished with value: 0.8576314411962564 and parameters: {'n_neighbors': 33, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.4639891538428149}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:57,554] Trial 31 finished with value: 0.8872181066088141 and parameters: {'n_neighbors': 15, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.46157665545154586}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:09:59,119] Trial 32 finished with value: 0.884627928327666 and parameters: {'n_neighbors': 12, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.44268449459219317}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:00,714] Trial 33 finished with value: 0.8872659024780242 and parameters: {'n_neighbors': 16, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.3681586702581581}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:02,251] Trial 34 finished with value: 0.8759272909812519 and parameters: {'n_neighbors': 8, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.3654168899049169}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:03,862] Trial 35 finished with value: 0.8781266677435646 and parameters: {'n_neighbors': 22, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.291882226011231}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:05,424] Trial 36 finished with value: 0.8868055796948835 and parameters: {'n_neighbors': 17, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.3573087191242933}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:05,842] Trial 37 finished with value: 0.8637076508151368 and parameters: {'n_neighbors': 30, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.4037881161472927, 'p': 2}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:07,439] Trial 38 finished with value: 0.8685910084468336 and parameters: {'n_neighbors': 41, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.25122476004857786}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:07,862] Trial 39 finished with value: 0.8652864480563695 and parameters: {'n_neighbors': 12, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.35801459553486487}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:09,514] Trial 40 finished with value: 0.8369961497488033 and parameters: {'n_neighbors': 87, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.4009267224829497}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:11,114] Trial 41 finished with value: 0.8872181066088141 and parameters: {'n_neighbors': 15, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.47150668192446143}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:12,702] Trial 42 finished with value: 0.884537192854032 and parameters: {'n_neighbors': 19, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.4397658133904145}. Best is trial 2 with value: 0.8872659024780242.
[I 2026-07-27 11:10:14,281] Trial 43 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.412733234083305}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:15,863] Trial 44 finished with value: 0.8810102666549435 and parameters: {'n_neighbors': 10, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.3772453223940446}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:17,445] Trial 45 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4982759788146636}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:19,015] Trial 46 finished with value: 0.8801524969379972 and parameters: {'n_neighbors': 21, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4972308272166309}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:20,627] Trial 47 finished with value: 0.8722454754947767 and parameters: {'n_neighbors': 7, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.4791971458969401}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:22,225] Trial 48 finished with value: 0.884627928327666 and parameters: {'n_neighbors': 12, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.4129728893069003, 'p': 1}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:23,674] Trial 49 finished with value: 0.8866522239647977 and parameters: {'n_neighbors': 18, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.12482797919866478}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:25,119] Trial 50 finished with value: 0.87882188038662 and parameters: {'n_neighbors': 9, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.49980614643891896}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:26,531] Trial 51 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.4425574047637655}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:28,001] Trial 52 finished with value: 0.8868464745562397 and parameters: {'n_neighbors': 13, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.4171350888239006}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:29,427] Trial 53 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.47825005263226694}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:30,849] Trial 54 finished with value: 0.8868464745562397 and parameters: {'n_neighbors': 13, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.4792204725289891}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:32,285] Trial 55 finished with value: 0.8834358431191329 and parameters: {'n_neighbors': 11, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.4542549925643635}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:32,668] Trial 56 finished with value: 0.8744111139964708 and parameters: {'n_neighbors': 20, 'leaf_size': 60, 'metric': 'euclidean', 'contamination': 0.433570957240472}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:34,098] Trial 57 finished with value: 0.8766053789011141 and parameters: {'n_neighbors': 23, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.4811895576390015}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:35,511] Trial 58 finished with value: 0.8868464745562397 and parameters: {'n_neighbors': 13, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.42164934636791324}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:35,893] Trial 59 finished with value: 0.8692744638172489 and parameters: {'n_neighbors': 14, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.39073809304658874, 'p': 2}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:37,292] Trial 60 finished with value: 0.8834358431191329 and parameters: {'n_neighbors': 11, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.44742967397832223}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:38,681] Trial 61 finished with value: 0.8872659024780242 and parameters: {'n_neighbors': 16, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.33859964858794134}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:40,119] Trial 62 finished with value: 0.8866522239647977 and parameters: {'n_neighbors': 18, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.4712864895445529}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:41,528] Trial 63 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4295682084158273}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:43,010] Trial 64 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.03894730719772882}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:44,449] Trial 65 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.19639440177776918}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:45,849] Trial 66 finished with value: 0.8834358431191329 and parameters: {'n_neighbors': 11, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.025734713500202788}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:47,249] Trial 67 finished with value: 0.87882188038662 and parameters: {'n_neighbors': 9, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.05510497992150534}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:48,667] Trial 68 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.17973747517814787}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:49,047] Trial 69 finished with value: 0.8654676634107542 and parameters: {'n_neighbors': 9, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.1293009077898259}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:50,448] Trial 70 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.10510217488374675}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:51,855] Trial 71 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.15596712036269367}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:53,264] Trial 72 finished with value: 0.8834358431191329 and parameters: {'n_neighbors': 11, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.2116019588587668}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:54,681] Trial 73 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.20174257560950618}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:56,100] Trial 74 finished with value: 0.8872659024780242 and parameters: {'n_neighbors': 16, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.18453238780782594}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:57,606] Trial 75 finished with value: 0.8866522239647977 and parameters: {'n_neighbors': 18, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.051837640445004524}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:10:59,042] Trial 76 finished with value: 0.884627928327666 and parameters: {'n_neighbors': 12, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.23021400615050025}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:11:00,459] Trial 77 finished with value: 0.8872181066088141 and parameters: {'n_neighbors': 15, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.09831042623294589}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:11:01,876] Trial 78 finished with value: 0.8868464745562397 and parameters: {'n_neighbors': 13, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.2706349688364797, 'p': 1}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:11:03,285] Trial 79 finished with value: 0.884537192854032 and parameters: {'n_neighbors': 19, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.1776670272757463}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:11:04,703] Trial 80 finished with value: 0.8868055796948835 and parameters: {'n_neighbors': 17, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.07535502783580747}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:11:06,118] Trial 81 finished with value: 0.8876735731271688 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.1401158363892535}. Best is trial 43 with value: 0.8876735731271688.
[I 2026-07-27 11:11:07,570] Trial 82 finished with value: 0.884627928327666 and parameters: {'n_neighbors': 12, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.09236981899607921}. Best is trial 43 with value: 0.8876735731271688.

,experiment_id,dataset_name,dataset_version,split_method,seed,preprocessing_version,model_type,fusion_strategy,hyperparameters,threshold,...,AUC_ROC,AUC_PR,Precision,Recall,F1,ConfusionMatrix,runtime_train,runtime_inference,memory_peak,notes
0,c278dda5-cfb1-4d09-80ec-b3cd40a206b6,CICIDS,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 42, 'leaf_size': 40, 'metric':...",7.906182e-11,...,0.798456,0.492324,0.483001,0.826058,0.609578,"[[54374, 21411], [4212, 20003]]",220.067883,143.144763,2089.921875,run1_small_opt_sample
1,91a03e98-3e85-4d4a-9618-e133b250c041,UNSW_NB15,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 14, 'leaf_size': 40, 'metric':...",5.167825e-12,...,0.896154,0.927284,0.773328,0.872033,0.819720,"[[25413, 11587], [5801, 39531]]",27.608088,59.974188,2393.875000,run1_small_opt_sample

In [9]:
rec = run_experiment(DATASETS[0], RUN_CONFIGS[1])
all_records.append(rec)
pd.DataFrame(all_records)

[I 2026-07-27 11:16:19,410] A new study created in memory with name: LOF_CICIDS_run2

CICIDS optuna subsample -> train: 21000, val: 9000 (val positives: 2177)

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-07-27 11:16:22,609] Trial 0 finished with value: 0.6710890190041237 and parameters: {'n_neighbors': 66, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.2757254682642995}. Best is trial 0 with value: 0.6710890190041237.
[I 2026-07-27 11:16:28,630] Trial 1 finished with value: 0.5971803872591497 and parameters: {'n_neighbors': 43, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.362951259351822, 'p': 1}. Best is trial 0 with value: 0.6710890190041237.
[I 2026-07-27 11:16:34,661] Trial 2 finished with value: 0.539928277662808 and parameters: {'n_neighbors': 16, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4220506703403939}. Best is trial 0 with value: 0.6710890190041237.
[I 2026-07-27 11:16:40,533] Trial 3 finished with value: 0.6565762430041705 and parameters: {'n_neighbors': 56, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.24751720505560543}. Best is trial 0 with value: 0.6710890190041237.
[I 2026-07-27 11:16:43,581] Trial 4 finished with value: 0.5713728949564051 and parameters: {'n_neighbors': 35, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.07322948745198661}. Best is trial 0 with value: 0.6710890190041237.
[I 2026-07-27 11:16:49,598] Trial 5 finished with value: 0.5563255036414904 and parameters: {'n_neighbors': 33, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.2505606416873945}. Best is trial 0 with value: 0.6710890190041237.
[I 2026-07-27 11:16:55,498] Trial 6 finished with value: 0.6150438501027793 and parameters: {'n_neighbors': 47, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.16069334497735088}. Best is trial 0 with value: 0.6710890190041237.
[I 2026-07-27 11:16:58,605] Trial 7 finished with value: 0.7003711742369951 and parameters: {'n_neighbors': 96, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.12591914309334096, 'p': 2}. Best is trial 7 with value: 0.7003711742369951.
[I 2026-07-27 11:17:04,630] Trial 8 finished with value: 0.6533833959295314 and parameters: {'n_neighbors': 55, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.028572769154841735}. Best is trial 7 with value: 0.7003711742369951.
[I 2026-07-27 11:17:07,644] Trial 9 finished with value: 0.6254376443372147 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.2059589309270761}. Best is trial 7 with value: 0.7003711742369951.
[I 2026-07-27 11:17:10,639] Trial 10 finished with value: 0.6473913418440465 and parameters: {'n_neighbors': 6, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.4896162581121494, 'p': 2}. Best is trial 7 with value: 0.7003711742369951.
[I 2026-07-27 11:17:13,759] Trial 11 finished with value: 0.6990860710460061 and parameters: {'n_neighbors': 88, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.11811230987643354}. Best is trial 7 with value: 0.7003711742369951.
[I 2026-07-27 11:17:16,859] Trial 12 finished with value: 0.6997170261816086 and parameters: {'n_neighbors': 94, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.10967638374671901, 'p': 2}. Best is trial 7 with value: 0.7003711742369951.
[I 2026-07-27 11:17:20,019] Trial 13 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.010714190847747274, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:23,130] Trial 14 finished with value: 0.7011216284513102 and parameters: {'n_neighbors': 98, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.017829280370784822, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:26,143] Trial 15 finished with value: 0.5538322142721486 and parameters: {'n_neighbors': 24, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.011981577315292547, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:32,081] Trial 16 finished with value: 0.6774233790421237 and parameters: {'n_neighbors': 73, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.05638716985836867, 'p': 1}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:35,046] Trial 17 finished with value: 0.6608798592617273 and parameters: {'n_neighbors': 5, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.07473265354475078, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:38,178] Trial 18 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.16845194788847007, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:44,041] Trial 19 finished with value: 0.6738463508448518 and parameters: {'n_neighbors': 68, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.3052981748392661, 'p': 1}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:47,065] Trial 20 finished with value: 0.5501972879296977 and parameters: {'n_neighbors': 25, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.1841144448584171, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:50,185] Trial 21 finished with value: 0.7016174318119742 and parameters: {'n_neighbors': 99, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.01620412156972669, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:53,261] Trial 22 finished with value: 0.6784922057314989 and parameters: {'n_neighbors': 71, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.14889106658986498, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:56,406] Trial 23 finished with value: 0.6903294478516456 and parameters: {'n_neighbors': 79, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.08135775087378086, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:17:59,472] Trial 24 finished with value: 0.6307694912590969 and parameters: {'n_neighbors': 55, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.20911205580008962, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:02,598] Trial 25 finished with value: 0.7016174318119742 and parameters: {'n_neighbors': 99, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.3367002917520652, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:05,663] Trial 26 finished with value: 0.5908978999198244 and parameters: {'n_neighbors': 44, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.056174449143883025, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:08,701] Trial 27 finished with value: 0.6632077686384733 and parameters: {'n_neighbors': 64, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.037489630993667644, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:14,692] Trial 28 finished with value: 0.6958437412542663 and parameters: {'n_neighbors': 82, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.0972589352208322, 'p': 1}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:17,761] Trial 29 finished with value: 0.6569157886962758 and parameters: {'n_neighbors': 62, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.1495778333396597}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:20,845] Trial 30 finished with value: 0.689736395804108 and parameters: {'n_neighbors': 78, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.23160707261213215}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:23,963] Trial 31 finished with value: 0.7011216284513102 and parameters: {'n_neighbors': 98, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.3193180007581492, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:27,081] Trial 32 finished with value: 0.7016174318119742 and parameters: {'n_neighbors': 99, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.37802789814049165, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:30,217] Trial 33 finished with value: 0.688774579698177 and parameters: {'n_neighbors': 77, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.44485643099271155, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:33,292] Trial 34 finished with value: 0.6136342995613676 and parameters: {'n_neighbors': 50, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.28869244946131756, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:36,372] Trial 35 finished with value: 0.6670758360004069 and parameters: {'n_neighbors': 65, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.3440493179937279, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:42,421] Trial 36 finished with value: 0.5801355435972697 and parameters: {'n_neighbors': 38, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.4072820586016898}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:45,428] Trial 37 finished with value: 0.6715533150020624 and parameters: {'n_neighbors': 9, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.263396117224904, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:51,535] Trial 38 finished with value: 0.6958437412542663 and parameters: {'n_neighbors': 82, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.04884421894763384}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:54,619] Trial 39 finished with value: 0.6413722910652861 and parameters: {'n_neighbors': 58, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.4844137296076104, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:18:57,687] Trial 40 finished with value: 0.6006948046715186 and parameters: {'n_neighbors': 40, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.18621392062602776}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:00,775] Trial 41 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.38522532166399337, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:03,868] Trial 42 finished with value: 0.6959270539922421 and parameters: {'n_neighbors': 85, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.3988670686726441, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:07,017] Trial 43 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.45163723815818824, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:13,112] Trial 44 finished with value: 0.6988769308274029 and parameters: {'n_neighbors': 85, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.43364426288467584}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:16,171] Trial 45 finished with value: 0.6203081716297607 and parameters: {'n_neighbors': 52, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.44781427767171444, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:19,298] Trial 46 finished with value: 0.6772858372856111 and parameters: {'n_neighbors': 70, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.46685802734154935, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:22,420] Trial 47 finished with value: 0.6983930100511854 and parameters: {'n_neighbors': 86, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.3711330219823188, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:25,599] Trial 48 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.029004396933049698, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:28,691] Trial 49 finished with value: 0.681250177144761 and parameters: {'n_neighbors': 74, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.13447150648326436}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:34,727] Trial 50 finished with value: 0.6637934151093019 and parameters: {'n_neighbors': 59, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.10274890826904898}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:37,856] Trial 51 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.012511582187087311, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:40,993] Trial 52 finished with value: 0.6995751084024953 and parameters: {'n_neighbors': 89, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.03755458901817698, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:44,096] Trial 53 finished with value: 0.6995751084024953 and parameters: {'n_neighbors': 89, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.07645652350746913, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:47,245] Trial 54 finished with value: 0.6790929663111563 and parameters: {'n_neighbors': 72, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.011486347797247443, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:50,362] Trial 55 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.05522099204593128, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:53,437] Trial 56 finished with value: 0.6710890190041237 and parameters: {'n_neighbors': 66, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.027741464548496804, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:56,538] Trial 57 finished with value: 0.6999352550625364 and parameters: {'n_neighbors': 90, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.4699741282600577, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:19:59,643] Trial 58 finished with value: 0.689736395804108 and parameters: {'n_neighbors': 78, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.09212797108677498, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:05,622] Trial 59 finished with value: 0.7019240900111494 and parameters: {'n_neighbors': 88, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.06600377644283548, 'p': 1}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:08,625] Trial 60 finished with value: 0.6270399418433328 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.4980124933905443, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:11,775] Trial 61 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.0475890703468914, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:14,915] Trial 62 finished with value: 0.6997170261816086 and parameters: {'n_neighbors': 94, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.029278745403679793, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:18,235] Trial 63 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.058257097207985956, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:21,490] Trial 64 finished with value: 0.681250177144761 and parameters: {'n_neighbors': 74, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.010649280679551953, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:24,663] Trial 65 finished with value: 0.689736395804108 and parameters: {'n_neighbors': 78, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.2333674193938019, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:27,894] Trial 66 finished with value: 0.6990860710460061 and parameters: {'n_neighbors': 88, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.11814145521146173, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:30,983] Trial 67 finished with value: 0.6732881723312708 and parameters: {'n_neighbors': 67, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.08434703307742614}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:34,059] Trial 68 finished with value: 0.6916629229232288 and parameters: {'n_neighbors': 81, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.035382598464759635, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:37,171] Trial 69 finished with value: 0.7003860527138376 and parameters: {'n_neighbors': 91, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.4019976075691173, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:43,110] Trial 70 finished with value: 0.6684619243283361 and parameters: {'n_neighbors': 62, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.18613312799395595}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:46,261] Trial 71 finished with value: 0.7022027753273922 and parameters: {'n_neighbors': 100, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.040994513699249294, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:49,404] Trial 72 finished with value: 0.7016174318119742 and parameters: {'n_neighbors': 99, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.061802316521396915, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:52,535] Trial 73 finished with value: 0.6938929440405674 and parameters: {'n_neighbors': 83, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.048517260113707196, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:55,603] Trial 74 finished with value: 0.6784922057314989 and parameters: {'n_neighbors': 71, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.16634478531172134, 'p': 2}. Best is trial 13 with value: 0.7022027753273922.
[I 2026-07-27 11:20:58,715] Trial 75 finished with value: 0.7024266593759886 and parameters: {'n_neighbors': 93, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.024384769785256118, 'p': 2}. Best is trial 75 with value: 0.7024266593759886.
[I 2026-07-27 11:21:01,816] Trial 76 finished with value: 0.7003860527138376 and parameters: {'n_neighbors': 91, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.026224903970772692, 'p': 2}. Best is trial 75 with value: 0.7024266593759886.
[I 2026-07-27 11:21:04,873] Trial 77 finished with value: 0.6910475868221398 and parameters: {'n_neighbors': 80, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.026022144045181383, 'p': 2}. Best is trial 75 with value: 0.7024266593759886.
[I 2026-07-27 11:21:07,976] Trial 78 finished with value: 0.6880819563056162 and parameters: {'n_neighbors': 76, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.06927050366165349, 'p': 2}. Best is trial 75 with value: 0.7024266593759886.
[I 2026-07-27 11:21:11,063] Trial 79 finished with value: 0.7010185899499187 and parameters: {'n_neighbors': 92, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.2876407805725326}. Best is trial 75 with value: 0.7024266593759886.
[I 2026-07-27 11:21:16,854] Trial 80 finished with value: 0.5255795351869581 and parameters: {'n_neighbors': 25, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.41822276125369096, 'p': 1}. Best is trial 75 with value: 0.7024266593759886.

,experiment_id,dataset_name,dataset_version,split_method,seed,preprocessing_version,model_type,fusion_strategy,hyperparameters,threshold,...,AUC_ROC,AUC_PR,Precision,Recall,F1,ConfusionMatrix,runtime_train,runtime_inference,memory_peak,notes
0,c278dda5-cfb1-4d09-80ec-b3cd40a206b6,CICIDS,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 42, 'leaf_size': 40, 'metric':...",7.906182e-11,...,0.798456,0.492324,0.483001,0.826058,0.609578,"[[54374, 21411], [4212, 20003]]",220.067883,143.144763,2089.921875,run1_small_opt_sample
1,91a03e98-3e85-4d4a-9618-e133b250c041,UNSW_NB15,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 14, 'leaf_size': 40, 'metric':...",5.167825e-12,...,0.896154,0.927284,0.773328,0.872033,0.819720,"[[25413, 11587], [5801, 39531]]",27.608088,59.974188,2393.875000,run1_small_opt_sample
2,8ca423e4-6f7e-4193-b04f-7212104a9116,CICIDS,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 100, 'leaf_size': 20, 'metric'...",6.054940e-11,...,0.811459,0.440691,0.482514,0.873467,0.621631,"[[53101, 22684], [3064, 21151]]",166.370851,109.645365,2481.906250,run2_medium_opt_sample

In [10]:
rec = run_experiment(DATASETS[1], RUN_CONFIGS[1])
all_records.append(rec)
pd.DataFrame(all_records)

[I 2026-07-27 11:39:31,718] A new study created in memory with name: LOF_UNSW_NB15_run2

UNSW_NB15 optuna subsample -> train: 21000, val: 9000 (val positives: 6126)

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-07-27 11:39:35,311] Trial 0 finished with value: 0.8777401261061208 and parameters: {'n_neighbors': 66, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.2757254682642995}. Best is trial 0 with value: 0.8777401261061208.
[I 2026-07-27 11:39:47,798] Trial 1 finished with value: 0.9006278440388129 and parameters: {'n_neighbors': 43, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.362951259351822, 'p': 1}. Best is trial 1 with value: 0.9006278440388129.
[I 2026-07-27 11:40:00,072] Trial 2 finished with value: 0.8758590192821543 and parameters: {'n_neighbors': 16, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4220506703403939}. Best is trial 1 with value: 0.9006278440388129.
[I 2026-07-27 11:40:12,482] Trial 3 finished with value: 0.8969573030384201 and parameters: {'n_neighbors': 56, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.24751720505560543}. Best is trial 1 with value: 0.9006278440388129.
[I 2026-07-27 11:40:15,977] Trial 4 finished with value: 0.866497560735117 and parameters: {'n_neighbors': 35, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.07322948745198661}. Best is trial 1 with value: 0.9006278440388129.
[I 2026-07-27 11:40:28,241] Trial 5 finished with value: 0.8946391607829184 and parameters: {'n_neighbors': 33, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.2505606416873945}. Best is trial 1 with value: 0.9006278440388129.
[I 2026-07-27 11:40:40,610] Trial 6 finished with value: 0.9007237765677443 and parameters: {'n_neighbors': 47, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.16069334497735088}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:40:44,204] Trial 7 finished with value: 0.8675690629010678 and parameters: {'n_neighbors': 96, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.12591914309334096, 'p': 2}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:40:56,560] Trial 8 finished with value: 0.8970226496189623 and parameters: {'n_neighbors': 55, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.028572769154841735}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:41:00,001] Trial 9 finished with value: 0.8682307644771784 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.2059589309270761}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:41:12,267] Trial 10 finished with value: 0.8597876227612619 and parameters: {'n_neighbors': 6, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.4896162581121494}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:41:24,453] Trial 11 finished with value: 0.8906691501207193 and parameters: {'n_neighbors': 30, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.3478952578979518, 'p': 1}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:41:36,683] Trial 12 finished with value: 0.8767977267455347 and parameters: {'n_neighbors': 20, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.160444387733593, 'p': 1}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:41:40,315] Trial 13 finished with value: 0.8667961784206449 and parameters: {'n_neighbors': 100, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.345884019901244, 'p': 2}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:41:52,650] Trial 14 finished with value: 0.9005449467469389 and parameters: {'n_neighbors': 45, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.3322878647626844, 'p': 1}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:42:04,932] Trial 15 finished with value: 0.8804099357700764 and parameters: {'n_neighbors': 23, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.4320806397597473}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:42:08,398] Trial 16 finished with value: 0.7431572673235745 and parameters: {'n_neighbors': 10, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.12356768762297005, 'p': 2}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:42:20,828] Trial 17 finished with value: 0.8956414824750751 and parameters: {'n_neighbors': 67, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.013088694269971751}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:42:33,188] Trial 18 finished with value: 0.8997227896384237 and parameters: {'n_neighbors': 40, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.19139327746191448, 'p': 1}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:42:36,656] Trial 19 finished with value: 0.8601222790433602 and parameters: {'n_neighbors': 27, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.40308123346470454}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:42:48,953] Trial 20 finished with value: 0.864939807307957 and parameters: {'n_neighbors': 8, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.28750328850278084}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:43:01,306] Trial 21 finished with value: 0.9005354330118316 and parameters: {'n_neighbors': 44, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.3433373474469739, 'p': 1}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:43:13,837] Trial 22 finished with value: 0.8937069567384621 and parameters: {'n_neighbors': 72, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.4902535804904484, 'p': 1}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:43:26,161] Trial 23 finished with value: 0.9007237765677443 and parameters: {'n_neighbors': 47, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.31071899363692085, 'p': 1}. Best is trial 6 with value: 0.9007237765677443.
[I 2026-07-27 11:43:38,447] Trial 24 finished with value: 0.9008145688397969 and parameters: {'n_neighbors': 49, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.3866602269741362, 'p': 1}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:43:50,998] Trial 25 finished with value: 0.8969573030384201 and parameters: {'n_neighbors': 56, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.2982771240446761, 'p': 1}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:44:03,563] Trial 26 finished with value: 0.8888195380198389 and parameters: {'n_neighbors': 86, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.3917376430614888, 'p': 1}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:44:07,066] Trial 27 finished with value: 0.8630768475787174 and parameters: {'n_neighbors': 25, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.44199303118685956}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:44:10,656] Trial 28 finished with value: 0.8755193363400144 and parameters: {'n_neighbors': 76, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.09888719696265756, 'p': 2}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:44:23,066] Trial 29 finished with value: 0.9008145688397969 and parameters: {'n_neighbors': 49, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.2145788689904727}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:44:35,487] Trial 30 finished with value: 0.8964073807500162 and parameters: {'n_neighbors': 58, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.2032860143334956}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:44:47,848] Trial 31 finished with value: 0.9008145688397969 and parameters: {'n_neighbors': 49, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.242783024052139}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:45:00,181] Trial 32 finished with value: 0.8981409820810077 and parameters: {'n_neighbors': 37, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.2463618960866415}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:45:12,549] Trial 33 finished with value: 0.9008145688397969 and parameters: {'n_neighbors': 49, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.18723152700481194}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:45:25,049] Trial 34 finished with value: 0.8936276945453753 and parameters: {'n_neighbors': 65, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.22848141809659167}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:45:37,285] Trial 35 finished with value: 0.8920311761975549 and parameters: {'n_neighbors': 31, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.1839494774335843}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:45:49,582] Trial 36 finished with value: 0.8981409820810077 and parameters: {'n_neighbors': 37, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.25982336779240517}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:46:01,941] Trial 37 finished with value: 0.9005694268653338 and parameters: {'n_neighbors': 51, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.15078296266865282}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:46:14,410] Trial 38 finished with value: 0.8914418358066772 and parameters: {'n_neighbors': 78, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.2258775413755811}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:46:26,666] Trial 39 finished with value: 0.8763530519267045 and parameters: {'n_neighbors': 19, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.37847569506584855}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:46:30,222] Trial 40 finished with value: 0.8790750309380987 and parameters: {'n_neighbors': 62, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.08746152602125876}. Best is trial 24 with value: 0.9008145688397969.
[I 2026-07-27 11:46:42,597] Trial 41 finished with value: 0.9008153924168658 and parameters: {'n_neighbors': 48, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.1667965740091007}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:46:54,940] Trial 42 finished with value: 0.8999808248538973 and parameters: {'n_neighbors': 41, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.1645390126949304}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:47:07,289] Trial 43 finished with value: 0.9005694268653338 and parameters: {'n_neighbors': 51, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.13261240866689492}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:47:19,666] Trial 44 finished with value: 0.8976081845157967 and parameters: {'n_neighbors': 36, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.043820708730859026}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:47:32,140] Trial 45 finished with value: 0.8932206770780439 and parameters: {'n_neighbors': 32, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.21600945471242808}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:47:44,463] Trial 46 finished with value: 0.8977462330720833 and parameters: {'n_neighbors': 52, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.18392525708391952}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:47:56,893] Trial 47 finished with value: 0.8901880675155985 and parameters: {'n_neighbors': 82, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.24942559214800883}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:48:00,481] Trial 48 finished with value: 0.8790750309380987 and parameters: {'n_neighbors': 62, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.31989577561249544}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:48:12,916] Trial 49 finished with value: 0.9006278440388129 and parameters: {'n_neighbors': 43, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.27537024936130183}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:48:25,335] Trial 50 finished with value: 0.9008145688397969 and parameters: {'n_neighbors': 49, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4602528474933328}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:48:37,830] Trial 51 finished with value: 0.9007237765677443 and parameters: {'n_neighbors': 47, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4548317520518315}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:48:50,314] Trial 52 finished with value: 0.8997227896384237 and parameters: {'n_neighbors': 40, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.4715129239173443}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:49:02,769] Trial 53 finished with value: 0.8891585393809563 and parameters: {'n_neighbors': 29, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.41453816114077957}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:49:15,133] Trial 54 finished with value: 0.8969573030384201 and parameters: {'n_neighbors': 56, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.1386746147234431}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:49:27,625] Trial 55 finished with value: 0.8952669537031548 and parameters: {'n_neighbors': 68, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.16900570786931343}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:49:40,066] Trial 56 finished with value: 0.8958107701615642 and parameters: {'n_neighbors': 34, 'leaf_size': 50, 'metric': 'manhattan', 'contamination': 0.467144864927714}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:49:52,429] Trial 57 finished with value: 0.8592841899784416 and parameters: {'n_neighbors': 5, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.3638801123315055}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:49:56,033] Trial 58 finished with value: 0.8687180665091305 and parameters: {'n_neighbors': 90, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.11052850214337973}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:50:08,513] Trial 59 finished with value: 0.9008145688397969 and parameters: {'n_neighbors': 49, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.06484311888251384}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:50:11,997] Trial 60 finished with value: 0.8756510234734232 and parameters: {'n_neighbors': 41, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.19801958315128565, 'p': 2}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:50:24,332] Trial 61 finished with value: 0.9008145688397969 and parameters: {'n_neighbors': 49, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.050006754842283424}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:50:36,721] Trial 62 finished with value: 0.8969573030384201 and parameters: {'n_neighbors': 56, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.27330715851241805}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:50:49,109] Trial 63 finished with value: 0.9007237765677443 and parameters: {'n_neighbors': 47, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.05593484644027939}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:51:01,592] Trial 64 finished with value: 0.8941109638896103 and parameters: {'n_neighbors': 71, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.01198368955966525}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:51:13,958] Trial 65 finished with value: 0.8947106131934547 and parameters: {'n_neighbors': 62, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.14604590780232685}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:51:17,462] Trial 66 finished with value: 0.873305873569901 and parameters: {'n_neighbors': 39, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.07949152145184402, 'p': 2}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:51:29,786] Trial 67 finished with value: 0.8975367605044698 and parameters: {'n_neighbors': 53, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.23674453383849559}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:51:42,102] Trial 68 finished with value: 0.9006278440388129 and parameters: {'n_neighbors': 43, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.11240476781540243}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:51:45,590] Trial 69 finished with value: 0.8606755240392491 and parameters: {'n_neighbors': 28, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.4335749185638802, 'p': 2}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:51:49,047] Trial 70 finished with value: 0.8651873064167899 and parameters: {'n_neighbors': 12, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.18327228634437648}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:52:01,352] Trial 71 finished with value: 0.9008145688397969 and parameters: {'n_neighbors': 49, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.03421601356447124}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:52:13,810] Trial 72 finished with value: 0.8961286993093993 and parameters: {'n_neighbors': 59, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.21003223685560182}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:52:26,366] Trial 73 finished with value: 0.9005449467469389 and parameters: {'n_neighbors': 45, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.0656967624356144}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:52:38,680] Trial 74 finished with value: 0.9007267016862995 and parameters: {'n_neighbors': 50, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.0276430515314888}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:52:50,967] Trial 75 finished with value: 0.8981409820810077 and parameters: {'n_neighbors': 37, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.055139183928240215}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:53:03,319] Trial 76 finished with value: 0.8958107701615642 and parameters: {'n_neighbors': 34, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.4981587363757126}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:53:06,865] Trial 77 finished with value: 0.8777401261061208 and parameters: {'n_neighbors': 66, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.09809319709579778, 'p': 2}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:53:19,307] Trial 78 finished with value: 0.9005354330118316 and parameters: {'n_neighbors': 44, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.39213185796130495}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:53:31,730] Trial 79 finished with value: 0.892203247006553 and parameters: {'n_neighbors': 76, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.22380725483851913}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:53:44,118] Trial 80 finished with value: 0.8972264707439297 and parameters: {'n_neighbors': 54, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.29194802055908115}. Best is trial 41 with value: 0.9008153924168658.
[I 2026-07-27 11:53:56,527] Trial 81 finished with value: 0.9008153924168658 and parameters: {'n_neighbors': 48, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.028905065265131848}. Best is trial 41 with value: 0.9008153924168658.

,experiment_id,dataset_name,dataset_version,split_method,seed,preprocessing_version,model_type,fusion_strategy,hyperparameters,threshold,...,AUC_ROC,AUC_PR,Precision,Recall,F1,ConfusionMatrix,runtime_train,runtime_inference,memory_peak,notes
0,c278dda5-cfb1-4d09-80ec-b3cd40a206b6,CICIDS,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 42, 'leaf_size': 40, 'metric':...",7.906182e-11,...,0.798456,0.492324,0.483001,0.826058,0.609578,"[[54374, 21411], [4212, 20003]]",220.067883,143.144763,2089.921875,run1_small_opt_sample
1,91a03e98-3e85-4d4a-9618-e133b250c041,UNSW_NB15,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 14, 'leaf_size': 40, 'metric':...",5.167825e-12,...,0.896154,0.927284,0.773328,0.872033,0.819720,"[[25413, 11587], [5801, 39531]]",27.608088,59.974188,2393.875000,run1_small_opt_sample
2,8ca423e4-6f7e-4193-b04f-7212104a9116,CICIDS,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 100, 'leaf_size': 20, 'metric'...",6.054940e-11,...,0.811459,0.440691,0.482514,0.873467,0.621631,"[[53101, 22684], [3064, 21151]]",166.370851,109.645365,2481.906250,run2_medium_opt_sample
3,b129d525-e0f6-4aa7-8ae6-d0b0e0f871af,UNSW_NB15,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 48, 'leaf_size': 30, 'metric':...",7.278875e-12,...,0.896950,0.918083,0.730715,0.906446,0.809149,"[[21857, 15143], [4241, 41091]]",29.233860,60.652467,2425.179688,run2_medium_opt_sample

In [11]:
rec = run_experiment(DATASETS[0], RUN_CONFIGS[2])
all_records.append(rec)
pd.DataFrame(all_records)

[I 2026-07-27 12:19:40,056] A new study created in memory with name: LOF_CICIDS_run3

CICIDS optuna subsample -> train: 35000, val: 15000 (val positives: 3629)

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-07-27 12:19:48,174] Trial 0 finished with value: 0.5917905015681555 and parameters: {'n_neighbors': 66, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.2757254682642995}. Best is trial 0 with value: 0.5917905015681555.
[I 2026-07-27 12:20:04,125] Trial 1 finished with value: 0.5259932307871112 and parameters: {'n_neighbors': 43, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.362951259351822, 'p': 1}. Best is trial 0 with value: 0.5917905015681555.
[I 2026-07-27 12:20:21,209] Trial 2 finished with value: 0.5540896178802176 and parameters: {'n_neighbors': 16, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4220506703403939}. Best is trial 0 with value: 0.5917905015681555.
[I 2026-07-27 12:20:37,343] Trial 3 finished with value: 0.5627919534154544 and parameters: {'n_neighbors': 56, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.24751720505560543}. Best is trial 0 with value: 0.5917905015681555.
[I 2026-07-27 12:20:45,223] Trial 4 finished with value: 0.5575168993440721 and parameters: {'n_neighbors': 35, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.07322948745198661}. Best is trial 0 with value: 0.5917905015681555.
[I 2026-07-27 12:21:01,191] Trial 5 finished with value: 0.5139462618027872 and parameters: {'n_neighbors': 33, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.2505606416873945}. Best is trial 0 with value: 0.5917905015681555.
[I 2026-07-27 12:21:17,000] Trial 6 finished with value: 0.5291395501975398 and parameters: {'n_neighbors': 47, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.16069334497735088}. Best is trial 0 with value: 0.5917905015681555.
[I 2026-07-27 12:21:25,168] Trial 7 finished with value: 0.6492584373251182 and parameters: {'n_neighbors': 96, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.12591914309334096, 'p': 2}. Best is trial 7 with value: 0.6492584373251182.
[I 2026-07-27 12:21:40,980] Trial 8 finished with value: 0.5602454349179417 and parameters: {'n_neighbors': 55, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.028572769154841735}. Best is trial 7 with value: 0.6492584373251182.
[I 2026-07-27 12:21:48,820] Trial 9 finished with value: 0.6586934576287098 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.2059589309270761}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:21:56,636] Trial 10 finished with value: 0.6128134133038804 and parameters: {'n_neighbors': 6, 'leaf_size': 60, 'metric': 'euclidean', 'contamination': 0.4896162581121494}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:22:04,513] Trial 11 finished with value: 0.6485984164102389 and parameters: {'n_neighbors': 5, 'leaf_size': 40, 'metric': 'minkowski', 'contamination': 0.13750771800782502, 'p': 2}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:22:12,407] Trial 12 finished with value: 0.6541792596545689 and parameters: {'n_neighbors': 11, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.13957727895746755, 'p': 2}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:22:20,326] Trial 13 finished with value: 0.6541792596545689 and parameters: {'n_neighbors': 11, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.19106060273353204}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:22:35,979] Trial 14 finished with value: 0.5421592842558332 and parameters: {'n_neighbors': 17, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.20853576807226037, 'p': 1}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:22:43,985] Trial 15 finished with value: 0.6417010451793235 and parameters: {'n_neighbors': 9, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.2992034043083919}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:22:51,923] Trial 16 finished with value: 0.6126433917611136 and parameters: {'n_neighbors': 18, 'leaf_size': 50, 'metric': 'minkowski', 'contamination': 0.0822203115922458, 'p': 2}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:23:07,952] Trial 17 finished with value: 0.5131208479247691 and parameters: {'n_neighbors': 25, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.32614124489400137, 'p': 1}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:23:15,844] Trial 18 finished with value: 0.6504548645753936 and parameters: {'n_neighbors': 10, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.021850992533385433}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:23:23,791] Trial 19 finished with value: 0.6232024541456188 and parameters: {'n_neighbors': 7, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.09050721552961874, 'p': 2}. Best is trial 9 with value: 0.6586934576287098.
[I 2026-07-27 12:23:31,658] Trial 20 finished with value: 0.6604902795102303 and parameters: {'n_neighbors': 12, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.1978188361553306}. Best is trial 20 with value: 0.6604902795102303.
[I 2026-07-27 12:23:39,499] Trial 21 finished with value: 0.6604902795102303 and parameters: {'n_neighbors': 12, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.202829865036649}. Best is trial 20 with value: 0.6604902795102303.
[I 2026-07-27 12:23:47,411] Trial 22 finished with value: 0.6586934576287098 and parameters: {'n_neighbors': 14, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.207926361396979}. Best is trial 20 with value: 0.6604902795102303.
[I 2026-07-27 12:23:55,278] Trial 23 finished with value: 0.5738666298771324 and parameters: {'n_neighbors': 24, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.18753325089310927}. Best is trial 20 with value: 0.6604902795102303.
[I 2026-07-27 12:24:03,153] Trial 24 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.23887490417625745}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:24:11,130] Trial 25 finished with value: 0.6232024541456188 and parameters: {'n_neighbors': 7, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.3314180456361122}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:24:19,096] Trial 26 finished with value: 0.5936451443449213 and parameters: {'n_neighbors': 21, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.23586042281184008}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:24:27,034] Trial 27 finished with value: 0.6198177871177614 and parameters: {'n_neighbors': 8, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.2835454650835326}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:24:34,923] Trial 28 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.37904846310917384}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:24:42,799] Trial 29 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.3906560802688236}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:24:50,666] Trial 30 finished with value: 0.6136825442376499 and parameters: {'n_neighbors': 20, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.4131360328052628}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:24:58,562] Trial 31 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.399247566079689}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:25:06,408] Trial 32 finished with value: 0.6586934576287098 and parameters: {'n_neighbors': 14, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.3945567996829306}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:25:14,241] Trial 33 finished with value: 0.6417010451793235 and parameters: {'n_neighbors': 9, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.4752665787385111}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:25:22,186] Trial 34 finished with value: 0.6131834936901919 and parameters: {'n_neighbors': 15, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.3739837972128366}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:25:30,138] Trial 35 finished with value: 0.5732763405741848 and parameters: {'n_neighbors': 27, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.4399271817027448}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:25:38,058] Trial 36 finished with value: 0.6126433917611136 and parameters: {'n_neighbors': 18, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.35273941593689306}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:25:54,178] Trial 37 finished with value: 0.5170567884796544 and parameters: {'n_neighbors': 31, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4337088789176238}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:26:02,106] Trial 38 finished with value: 0.6604902795102303 and parameters: {'n_neighbors': 12, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.45952806890328196}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:26:18,046] Trial 39 finished with value: 0.6123038939271072 and parameters: {'n_neighbors': 9, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.38765548655239424}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:26:26,039] Trial 40 finished with value: 0.6131834936901919 and parameters: {'n_neighbors': 15, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.3424209943529232}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:26:33,877] Trial 41 finished with value: 0.6604902795102303 and parameters: {'n_neighbors': 12, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.30774739772135123}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:26:41,665] Trial 42 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.4142472148702109}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:26:49,537] Trial 43 finished with value: 0.5936451443449213 and parameters: {'n_neighbors': 21, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.4094148107619804}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:26:57,393] Trial 44 finished with value: 0.6504548645753936 and parameters: {'n_neighbors': 10, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.3703818609633196}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:27:13,004] Trial 45 finished with value: 0.5540896178802176 and parameters: {'n_neighbors': 16, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.4987134733535072}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:27:20,904] Trial 46 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.4475551497155612}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:27:28,757] Trial 47 finished with value: 0.6485984164102389 and parameters: {'n_neighbors': 5, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.2692874989865433}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:27:36,629] Trial 48 finished with value: 0.6120051082071041 and parameters: {'n_neighbors': 19, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.40190988851824355}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:27:44,449] Trial 49 finished with value: 0.6232024541456188 and parameters: {'n_neighbors': 7, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.46724358679816713}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:28:00,163] Trial 50 finished with value: 0.6165762425573469 and parameters: {'n_neighbors': 10, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.4218254305782898}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:28:08,004] Trial 51 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.43984569384471417}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:28:15,844] Trial 52 finished with value: 0.6141907913608604 and parameters: {'n_neighbors': 17, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.45057854959218413}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:28:24,128] Trial 53 finished with value: 0.6516457666101971 and parameters: {'n_neighbors': 97, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.3858772003219299}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:28:31,941] Trial 54 finished with value: 0.6541792596545689 and parameters: {'n_neighbors': 11, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.35860786464943184}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:28:39,803] Trial 55 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.41421019438285334}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:28:55,622] Trial 56 finished with value: 0.5928797444849565 and parameters: {'n_neighbors': 70, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.4790159448909853, 'p': 1}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:29:03,537] Trial 57 finished with value: 0.6198177871177614 and parameters: {'n_neighbors': 8, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.3198931689533709}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:29:11,395] Trial 58 finished with value: 0.6131834936901919 and parameters: {'n_neighbors': 15, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.0470137953739819}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:29:19,247] Trial 59 finished with value: 0.5781114735970188 and parameters: {'n_neighbors': 23, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.24116882109943527}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:29:34,900] Trial 60 finished with value: 0.6228294294010625 and parameters: {'n_neighbors': 11, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.37533354054363277, 'p': 1}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:29:42,707] Trial 61 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.4405777235929288}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:29:50,575] Trial 62 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.42554818545091233}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:29:58,468] Trial 63 finished with value: 0.6174054731960529 and parameters: {'n_neighbors': 16, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.45151331345943185}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:30:06,308] Trial 64 finished with value: 0.6504548645753936 and parameters: {'n_neighbors': 10, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.3973108848631541}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:30:14,142] Trial 65 finished with value: 0.6586934576287098 and parameters: {'n_neighbors': 14, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.34567650625971874}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:30:21,983] Trial 66 finished with value: 0.6141907913608604 and parameters: {'n_neighbors': 17, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.16653736502527675}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:30:29,809] Trial 67 finished with value: 0.6198177871177614 and parameters: {'n_neighbors': 8, 'leaf_size': 30, 'metric': 'euclidean', 'contamination': 0.11144916151580417}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:30:37,626] Trial 68 finished with value: 0.6417010451793235 and parameters: {'n_neighbors': 9, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.48788237912461463}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:30:45,496] Trial 69 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.4317576318397419}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:31:01,447] Trial 70 finished with value: 0.6228294294010625 and parameters: {'n_neighbors': 11, 'leaf_size': 30, 'metric': 'minkowski', 'contamination': 0.45805337341988994, 'p': 1}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:31:09,329] Trial 71 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.4161640021677385}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:31:17,220] Trial 72 finished with value: 0.6604902795102303 and parameters: {'n_neighbors': 12, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.38633380631256103}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:31:25,079] Trial 73 finished with value: 0.6131834936901919 and parameters: {'n_neighbors': 15, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.40898393203795746}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:31:33,018] Trial 74 finished with value: 0.6504548645753936 and parameters: {'n_neighbors': 10, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.4407083701343017}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:31:48,725] Trial 75 finished with value: 0.5438398706285338 and parameters: {'n_neighbors': 18, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.3668380216920406}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:31:56,660] Trial 76 finished with value: 0.6586934576287098 and parameters: {'n_neighbors': 14, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.22637778077380522}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:32:04,551] Trial 77 finished with value: 0.6604902795102303 and parameters: {'n_neighbors': 12, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.4748498656644483}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:32:12,420] Trial 78 finished with value: 0.6136825442376499 and parameters: {'n_neighbors': 20, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.3357442792740246}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:32:20,383] Trial 79 finished with value: 0.6586934576287098 and parameters: {'n_neighbors': 14, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.2655792102130791}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:32:28,305] Trial 80 finished with value: 0.6174054731960529 and parameters: {'n_neighbors': 16, 'leaf_size': 10, 'metric': 'euclidean', 'contamination': 0.29361321269564955}. Best is trial 24 with value: 0.6640610227091446.
[I 2026-07-27 12:32:36,213] Trial 81 finished with value: 0.6640610227091446 and parameters: {'n_neighbors': 13, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.4423837527122602}. Best is trial 24 with value: 0.6640610227091446.

,experiment_id,dataset_name,dataset_version,split_method,seed,preprocessing_version,model_type,fusion_strategy,hyperparameters,threshold,...,AUC_ROC,AUC_PR,Precision,Recall,F1,ConfusionMatrix,runtime_train,runtime_inference,memory_peak,notes
0,c278dda5-cfb1-4d09-80ec-b3cd40a206b6,CICIDS,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 42, 'leaf_size': 40, 'metric':...",7.906182e-11,...,0.798456,0.492324,0.483001,0.826058,0.609578,"[[54374, 21411], [4212, 20003]]",220.067883,143.144763,2089.921875,run1_small_opt_sample
1,91a03e98-3e85-4d4a-9618-e133b250c041,UNSW_NB15,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 14, 'leaf_size': 40, 'metric':...",5.167825e-12,...,0.896154,0.927284,0.773328,0.872033,0.819720,"[[25413, 11587], [5801, 39531]]",27.608088,59.974188,2393.875000,run1_small_opt_sample
2,8ca423e4-6f7e-4193-b04f-7212104a9116,CICIDS,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 100, 'leaf_size': 20, 'metric'...",6.054940e-11,...,0.811459,0.440691,0.482514,0.873467,0.621631,"[[53101, 22684], [3064, 21151]]",166.370851,109.645365,2481.906250,run2_medium_opt_sample
3,b129d525-e0f6-4aa7-8ae6-d0b0e0f871af,UNSW_NB15,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 48, 'leaf_size': 30, 'metric':...",7.278875e-12,...,0.896950,0.918083,0.730715,0.906446,0.809149,"[[21857, 15143], [4241, 41091]]",29.233860,60.652467,2425.179688,run2_medium_opt_sample
4,dfcddaeb-79fd-4681-9ae0-17096d4ab0eb,CICIDS,v1,stratified_train_val_test_fixed_seed,29,v1,LOF,none,"{'n_neighbors': 13, 'leaf_size': 30, 'metric':...",8.137649e-10,...,0.853417,0.578099,0.631658,0.572001,0.600351,"[[67708, 8077], [10364, 13851]]",17.667551,11.611569,2458.714844,run3_large_opt_sample

In [8]:
rec = run_experiment(DATASETS[1], RUN_CONFIGS[2])
all_records.append(rec)
pd.DataFrame(all_records)

[I 2026-07-27 14:29:14,168] A new study created in memory with name: LOF_UNSW_NB15_run3

UNSW_NB15 optuna subsample -> train: 35000, val: 15000 (val positives: 10209)

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-07-27 14:29:25,551] Trial 0 finished with value: 0.8760852472614774 and parameters: {'n_neighbors': 66, 'leaf_size': 20, 'metric': 'euclidean', 'contamination': 0.2757254682642995}. Best is trial 0 with value: 0.8760852472614774.
[I 2026-07-27 14:30:06,098] Trial 1 finished with value: 0.8882429954506033 and parameters: {'n_neighbors': 43, 'leaf_size': 60, 'metric': 'minkowski', 'contamination': 0.362951259351822, 'p': 1}. Best is trial 1 with value: 0.8882429954506033.
[I 2026-07-27 14:30:49,478] Trial 2 finished with value: 0.8713268803893839 and parameters: {'n_neighbors': 16, 'leaf_size': 40, 'metric': 'manhattan', 'contamination': 0.4220506703403939}. Best is trial 1 with value: 0.8882429954506033.
[I 2026-07-27 14:31:31,972] Trial 3 finished with value: 0.8948630990711987 and parameters: {'n_neighbors': 56, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.24751720505560543}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:31:42,538] Trial 4 finished with value: 0.8639413302266497 and parameters: {'n_neighbors': 35, 'leaf_size': 50, 'metric': 'euclidean', 'contamination': 0.07322948745198661}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:32:25,978] Trial 5 finished with value: 0.8810013996964589 and parameters: {'n_neighbors': 33, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.2505606416873945}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:33:09,576] Trial 6 finished with value: 0.8912337448924655 and parameters: {'n_neighbors': 47, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.16069334497735088}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:33:20,186] Trial 7 finished with value: 0.8748666029636207 and parameters: {'n_neighbors': 96, 'leaf_size': 10, 'metric': 'minkowski', 'contamination': 0.12591914309334096, 'p': 2}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:34:04,265] Trial 8 finished with value: 0.8947213220727087 and parameters: {'n_neighbors': 55, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.028572769154841735}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:34:14,655] Trial 9 finished with value: 0.868654492838355 and parameters: {'n_neighbors': 14, 'leaf_size': 40, 'metric': 'euclidean', 'contamination': 0.2059589309270761}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:34:56,929] Trial 10 finished with value: 0.8632812580662566 and parameters: {'n_neighbors': 6, 'leaf_size': 60, 'metric': 'manhattan', 'contamination': 0.4896162581121494}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:35:40,134] Trial 11 finished with value: 0.8901991684174373 and parameters: {'n_neighbors': 98, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.011523253932588604}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:36:21,756] Trial 12 finished with value: 0.8762012122388276 and parameters: {'n_neighbors': 22, 'leaf_size': 10, 'metric': 'manhattan', 'contamination': 0.3245456521045245}. Best is trial 3 with value: 0.8948630990711987.
[I 2026-07-27 14:37:04,200] Trial 13 finished with value: 0.8952115358001284 and parameters: {'n_neighbors': 60, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.010903820425772457}. Best is trial 13 with value: 0.8952115358001284.
[I 2026-07-27 14:37:45,382] Trial 14 finished with value: 0.8968837254215123 and parameters: {'n_neighbors': 70, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.11764671537686079}. Best is trial 14 with value: 0.8968837254215123.
[I 2026-07-27 14:38:26,588] Trial 15 finished with value: 0.8778760801768606 and parameters: {'n_neighbors': 26, 'leaf_size': 20, 'metric': 'minkowski', 'contamination': 0.1036033564382962, 'p': 1}. Best is trial 14 with value: 0.8968837254215123.
[I 2026-07-27 14:39:08,688] Trial 16 finished with value: 0.8970224152000481 and parameters: {'n_neighbors': 76, 'leaf_size': 20, 'metric': 'manhattan', 'contamination': 0.16591367944415444}. Best is trial 16 with value: 0.8970224152000481.
[W 2026-07-27 14:39:39,696] Trial 17 failed with parameters: {'n_neighbors': 77, 'leaf_size': 30, 'metric': 'manhattan', 'contamination': 0.18000014601145126} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\aisia\AppData\Local\Temp\ipykernel_14228\543386532.py", line 25, in objective
    val_scores = -clf.score_samples(val_x)
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\sklearn\neighbors\_lof.py", line 476, in score_samples
    distances_X, neighbors_indices_X = self.kneighbors(
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\sklearn\neighbors\_base.py", line 906, in kneighbors
    chunked_results = list(
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\sklearn\metrics\pairwise.py", line 2240, in pairwise_distances_chunked
    D_chunk = pairwise_distances(X_chunk, Y, metric=metric, n_jobs=n_jobs, **kwds)
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\sklearn\metrics\pairwise.py", line 2476, in pairwise_distances
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\sklearn\metrics\pairwise.py", line 1965, in _parallel_pairwise
    Parallel(backend="threading", n_jobs=n_jobs)(
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\sklearn\utils\parallel.py", line 82, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\joblib\parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\joblib\parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "c:\Users\aisia\Desktop\Meisterstück\mgr inz\ver1004\hybrid_LUNAR\venv\lib\site-packages\joblib\parallel.py", line 1800, in _retrieve
    time.sleep(0.01)
KeyboardInterrupt
[W 2026-07-27 14:39:39,817] Trial 17 failed with value None.

KeyboardInterrupt: